### ISSUE TITLE
Migration tasks for jekyll-paginate-v2 project to jekyll

### ISSUE THREAD

**Issue by sverrirs** [sverrirs/jekyll-paginate-v2#50]
As discussed in this [issue thread #257](https://github.com/github/pages-gem/issues/257#issuecomment-347676497) then people seem relatively happy with the jekyll-paginate-v2 project taking over for the old jekyll-paginate. There are some improvements needed though before this can happen.

In this issue I want to collect the steps necessary to migrate this project to the larger Jekyll project umbrella. From this Epic-issue I'd then like to create and link actionable issues/tasks that break down the work into manageable chunks.

## Tasks
1. Test coverage needs to be improved
1.1. Unit tests need to be added to all major code paths. TODO Break down necessary areas for tests.
1.2. Integration tests should be considered. Actually testing how the plugin renders an example website may be necessary and useful as some idiosyncratic behaviors arise from interaction with Jekyll itself (e.g. date fields for drafts).

2. Introduction of new active collaborators to the project. 

3. Improving documentation. Some areas of the documentation could do with updating and a once-over to ensure that they're consistent and written in roughly the same style.

4. Adding more example projects. The examples have been a great resource for many people starting out with the plugin. A few more advanced ones or even fewer but more organized/aesthetically pleasing might be even more helpful.

**Comment by ashmaroli** [comment]
:+1: :+1:  on the `Epic` label. :smile: 

IMO, You *don't have to improve the project* to have it included under the Jekyll organisation (unless one of the maintainers there requested that privately), the improvements are only a necessity for inclusion in GitHub Pages environment, which is a separate concern by itself.

Either ways, I'm willing to lend a hand (not yet a consumer of this plugin, though).
I suggest that you reformat the task list above as checkboxes like below:

- [ ] Test coverage needs to be improved
  - [ ] Unit tests need to be added to all major code paths. TODO Break down necessary areas for tests.
  - [ ] Integration tests should be considered. Actually testing how the plugin renders an example website may be necessary and useful as some idiosyncratic behaviors arise from interaction with Jekyll itself (e.g. date fields for drafts).

**Comment by inwardmovement** [comment]
@sverrirs I don't have any Ruby skills but I might have time to contribute in a way or another. 
I am interested in this plugin being natively supported by the GitHub Pages integration/auto-build!

**Comment by ashmaroli** [comment]
@sverrirs Any updates on this..?

**Comment by sverrirs** [comment]
Hahaha no unfortunately I have zero time for this kind of thing at the moment.

Still am looking for serious collaborators to work on this project though :/

**Comment by ashmaroli** [comment]
Question to the Community:
  **Are there any benefactors willing to sponsor maintenance / collaboration on this plugin?**

If so, I'm willing to spend time on refactoring this plugin's source code..

**Comment by ashmaroli** [comment]
> it sounds a lot like you're trying to monitize on the work that I and others have done here for free

There's no way I could just take a software released under MIT and monetize upon the program. My proposal can be seen more like a freelancer canvassing a client to get paid for services rendered.

> How exactly do you see these proposed contributions being fairly funnelled to the maintenance and upkeep of this repo?

I was hoping to propose having an [OpenCollective Account](https://opencollective.com) primarily to stash sponsorship funds like how [Jekyll Core](https://opencollective.com/jekyll) does it currently.

> How should we measure success, quality and fairly divide these contributions among those that would contribute?

Good question. But unfortunately, there isn't a clear answer.
**You could use your expertise** to pre-assign tasks and segregate them into appropriate "difficulty-levels".
A contributor would then have an idea about what can be *expected* for their effort.
The gray area here is that the above step requires *you to invest time*, the lack of which is the primary reason you're looking for "help" from the community.

---

P.S. I can delete my proposal if you still think it is distasteful.. *and pretend that this conversation never happened..*

**Comment by sverrirs** [comment]
I appreciate what you're saying and understand where the idea is coming from. 

However adding actual real money to the mix has a tendency to complicates things and introduce conflicts that would not exist otherwise. Also the management of funds would need to be open for scrutiny by contributors and others, this means "paperwork" and honestly that time would be better spent on actual coding ;)

I am not against people offering bounties on particular features/requests/issues. I would be more than happy to facilitate something like that here (although the exchange of money would be strictly between the payer and payee). The payer could then simply comment on the issue or PR indicating that they are happy and I would merge and release that ASAP.  

But setting up a fund or raise a "pot of cash" is not something that I think would benefit this project at this point.

Don't delete anything, I'm glad that you brought this issue up and I really hope that you stick around even though we don't fully agree on this topic. Your contributions to this project are most welcome and appreciated :)

**Comment by fuzzy76** [comment]
Over at github/pages-gem#257 @parkr suggested adopting this project under the jekyll org in order to reduce the bus factor. Is this something you'd consider if it meant more developer audience and could be done without having all the tests in place?

**Comment by sverrirs** [comment]
@fuzzy I'd be honored and glad for the additional assistance with maintenance :)

**Comment by ashmaroli** [comment]
@fuzzy76 If you're fine with assessing Ruby code, I have numerous PRs open in this repository and any feedback would be appreciated..

**Comment by fuzzy76** [comment]
Sorry, I'm not. I'm just an end-user of Jekyll, trying to get this ball moving. I guess the next step for the solution I suggested is @sverrirs getting in touch with the folks over at https://github.com/jekyll

**Comment by ashmaroli** [comment]
@fuzzy76 Ok. No probs.
Incidentally, I'm part of a team that collectively maintain the plugins within the Jekyll Org.

From my experience, the situation at hand is a little complicated:
  - Simply moving a plugin to Jekyll Org doesn't guarantee an adoption by GitHub Pages. In fact they've still not adopted Jekyll v3.8.
  - The team at Jekyll itself is stretched thin. The development of v4.0 is going on at a slow pace.
  - Plugins at Jekyll follow a certain style of coding. This reduces the maintainer overhead from having to getting used to a "different style" of coding when reviewing PRs.. So, that means the existing code will need refactoring. But without proper test coverage, refactoring is a shot in the dark..

**Comment by ashmaroli** [comment]
@sverrirs Any feedback on the open PRs..?
I can submit additional PRs for tests if you're fine with move to RSpec-Core..

**Comment by sverrirs** [comment]
Given up on this, not a concern anymore

**Comment by DavidCao22** [comment]
@sverrirs Can I ask why you are giving up on this issue?

**Comment by sverrirs** [comment]
Being realistic, this is unfortunately never going to happen.
